Ignore L4-listener/TLS pool combination
sapcc/octavia-f5-provider-driver pull request #136
Opened 2021-08-16 10:12 UTC by laerlingSAP

clientTLS on L4 listeners cause AS3 errors like `Cannot read property 'undefined' of undefined`

Also: Optimize imports

2021-08-16 10:13 UTC, laerlingSAP commented
Added migration label, since this has to be ported to train-m3

2021-08-17 09:47 UTC, notandy requested changes

2021-08-17 09:47 UTC, notandy commented on octavia_f5/restclient/as3objects/service.py
> +        if pool.tls_enabled and listener.protocol not in [ const.PROTOCOL_TCP, const.PROTOCOL_UDP, const.PROTOCOL_HTTPS ]:
Please use a in [ .. ] condition instead of not in [ ... ] to make the condition clearer.

2021-08-17 11:06 UTC, notandy approved these changes

2021-08-17 12:22 UTC, merged