L2 dry run
sapcc/octavia-f5-provider-driver pull request #162
Opened 2022-04-04 16:00 UTC by laerlingSAP

2022-04-04 17:11 UTC, notandy requested changes

2022-04-04 17:11 UTC, notandy commented on octavia_f5/controller/worker/l2_sync_manager.py
> +            return []
Hrm, I don't like this, dry-run is not meant to completely ignore any (l2) action on devices, but rather not to do any modification but emitting correct logs.

It's true that dry-run hasn't been adapted for l2_sync_manager, but ignoring devices could be achieved by letting the  bigip_urls and vcmp_urls empty in the first place.

2022-04-05 15:31 UTC, BenjaminLudwigSAP commented on octavia_f5/controller/worker/l2_sync_manager.py
> +            return []
Yep, that's exactly the point I wanted to have your opinion on. But:
- iControl REST does not offer a dry-run parameter, so we're forced to refrain from sending anything when dry-run=True
- Leaving `bigip_urls` config option empty is not an option, because AS3 dry-runs wouldn't happen anymore.
- We could write a thin wrapper around the bigip module, but we'd have to wrap every method and make sure only the wrapper is used
- But all we'd get from that is a slightly deeper call chain.
  - For debugging it doesn't make sense, that's what unit tests are for
  - We only reach [one more log line](https://github.com/sapcc/octavia-f5-provider-driver/blob/stable/ussuri-m3/octavia_f5/controller/worker/l2_sync_manager.py#L112) that isn't reached when setting `self._bigips` and `self._vcmps` to `[]`, every other log line is outside of the loops that iterate over these lists.
  - We would still not reach error handling code, since no errors would occur, since we're not sending anything.

The thin wrapper idea is the only alternative I see, and I don't think it's worth it. Not substantially more logs, but more code than this here PR and more places to look out for when reviewing code and looking for wrapper bypasses...

2022-04-25 09:21 UTC, laerlingSAP commented
I'll merge this for now so I can use it on the stable/ussuri-m3 branch, but I will try getting this a bit more semantically correct as described above, once I get to it. For now this works without problems

2022-04-25 09:21 UTC, merged