[rescheduling] Add sanity check
sapcc/octavia-f5-provider-driver pull request #190
Opened 2022-11-29 16:59 UTC by BenjaminLudwigSAP

2022-11-29 17:48 UTC, notandy requested changes

2022-11-29 17:48 UTC, notandy commented on octavia_f5/api/drivers/f5_driver/tasks/reschedule_tasks.py
> +        if not self._amphora_repo.get_devices_for_host(candidate):
get_devices_for_host takes two parameters, not one: session and host.
I'd recommend you to add easy unit tests to your PRs.

2022-12-02 13:45 UTC, notandy requested changes
Could you split of the refactoring in a seperate PR, thanks.

2022-12-02 13:52 UTC, BenjaminLudwigSAP commented
Yeah, I was already contemplating doing that.

2023-04-12 12:45 UTC, BenjaminLudwigSAP commented
Replacing this PR with #216, which will be implemented via separate PRs.

2023-04-12 12:45 UTC, closed without merging