Add TLS 1.3 support for Server and Client Side
sapcc/octavia-f5-provider-driver pull request #246
Opened 2023-11-20 19:57 UTC by velp

This PR adds support for TLS 1.3 on Server and Client side. 3 new ciphers have to be added to the option: `tls_cipher_allow_list`:

- TLS13-AES128-GCM-SHA256
- TLS13-AES256-GCM-SHA384
 - TLS13-CHACHA20-POLY1305-SHA256

Documentation here: https://my.f5.com/manage/s/article/K10251520

Example of F5 declaration:
```
...
"tls_listener_f410ba56-2144-4b18-8eb4-4c61e423e962": {
    "certificates": [
        {
            "certificate": "cert_21d096e57a5d420cdc9cdd54ec97dbcb92952029"
        }
    ],
    "cipherGroup": {
        "use": "cipher_group_listener_f410ba56-2144-4b18-8eb4-4c61e423e962"
    },
    "class": "TLS_Server",
    "renegotiationEnabled": false,
    "sslEnabled": false,
    "tls1_0Enabled": false,
    "tls1_1Enabled": false,
    "tls1_2Enabled": true,
    "tls1_3Enabled": true
},
"cipher_rule_listener_f410ba56-2144-4b18-8eb4-4c61e423e962": {
    "cipherSuites": [
       ...
        "TLS13-AES128-GCM-SHA256",
        "TLS13-AES256-GCM-SHA384",
        "TLS13-CHACHA20-POLY1305-SHA256"
    ],
    "class": "Cipher_Rule"
},
...
``` 

Example of handshake (tested in QA):
```
# curl --http1.1 --tlsv1.3 --resolve example.com:4343:<IP> --cacert /test_ca.pem https://example.com:4343 -v
* Added example.com:4343:<IP> to DNS cache
* Hostname example.com was found in DNS cache
*   Trying 10.237.208.186:4343...
* Connected to example.com (10.237.208.186) port 4343
* ALPN: curl offers http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /test_ca.pem
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=NGINX, Inc.; CN=nginx-manager.example.com
*  start date: Sep 22 14:43:50 2023 GMT
*  expire date: Sep 19 14:43:50 2033 GMT
*  subjectAltName: host "example.com" matched cert's "example.com"
*  issuer: C=US; ST=California; L=San Francisco; O=NGINX, Inc.; CN=nms-int-ca
*  SSL certificate verify ok.
* using HTTP/1.1
> GET / HTTP/1.1
> Host: example.com:4343
> User-Agent: curl/8.4.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx
< Date: Mon, 20 Nov 2023 19:44:56 GMT
< Content-Type: text/html
< Content-Length: 157
< Last-Modified: Fri, 22 Sep 2023 11:57:42 GMT
< Connection: keep-alive
< ETag: "650d8136-9d"
< Accept-Ranges: bytes
<
<!DOCTYPE html>
<html>
<head>
<title>Answer from host test-lb-1</title>
</head>
<body>
<h1>Answer from host test-lb-1</h1>
</body>
</html>
* Connection #0 to host example.com left intact
```

OpenSSL check:
```
 $ openssl s_client -tls1_3 -connect <IP>:4343 -servername example.com -CAfile /test_ca.pem
CONNECTED(00000003)
depth=2 C = US, ST = California, L = San Francisco, O = "NGINX, Inc.", CN = nms-ca
verify return:1
depth=1 C = US, ST = California, L = San Francisco, O = "NGINX, Inc.", CN = nms-int-ca
verify return:1
depth=0 C = US, ST = California, L = San Francisco, O = "NGINX, Inc.", CN = nginx-manager.example.com
verify return:1
---
Certificate chain
 0 s:C = US, ST = California, L = San Francisco, O = "NGINX, Inc.", CN = nginx-manager.example.com
   i:C = US, ST = California, L = San Francisco, O = "NGINX, Inc.", CN = nms-int-ca
   a:PKEY: rsaEncryption, 4096 (bit); sigalg: RSA-SHA256
   v:NotBefore: Sep 22 14:43:50 2023 GMT; NotAfter: Sep 19 14:43:50 2033 GMT
---
Server certificate
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
subject=C = US, ST = California, L = San Francisco, O = "NGINX, Inc.", CN = nginx-manager.example.com
issuer=C = US, ST = California, L = San Francisco, O = "NGINX, Inc.", CN = nms-int-ca
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 2329 bytes and written 309 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_128_GCM_SHA256
Server public key is 4096 bit
This TLS version forbids renegotiation.
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

Also, this PR contains hardcoded disabling of SSLv3, TLSv1.0, and TLSv1.1 because, on the api level, they are not allowed, but we have to keep them in the code because we have to re-write default F5 values:
```
$ openstack loadbalancer listener set --tls-version "SSLv3" --tls-version "TLSv1.2" --tls-version "TLSv1.3" 6b8d4dc7-405c-4c7c-ab52-50a64fd42445
Validation failure: Requested TLS versions are less than the minimum: SSLv3 < TLSv1.2 (HTTP 400) (Request-ID: req-b1fa5d86-84b0-46ea-b1ca-2d1ab8309df0)

$ openstack loadbalancer listener set --tls-version "TLSv1.0" --tls-version "TLSv1.2" --tls-version "TLSv1.3" 6b8d4dc7-405c-4c7c-ab52-50a64fd42445
Validation failure: Invalid TLS versions: TLSv1.0 (HTTP 400) (Request-ID: req-cf6c8810-7e48-4e24-a5a5-b963b96aba00)

$ openstack loadbalancer listener set --tls-version "TLSv1.1" --tls-version "TLSv1.2" --tls-version "TLSv1.3" 6b8d4dc7-405c-4c7c-ab52-50a64fd42445
Validation failure: Requested TLS versions are less than the minimum: TLSv1.1 < TLSv1.2 (HTTP 400) (Request-ID: req-40b99e6a-c9b5-428b-88e1-151af8ad29da)
```

2023-11-21 07:39 UTC, m-kratochvil commented
I'm checking (the F5 and AS3 side of things mainly), will update here.

2023-11-21 10:37 UTC, m-kratochvil commented
After thorough discussion with @velp we agreed on following updates/changes.

**Octavia F5PD:**
* set TLSv1.2 as a default protocol version in `tls_versions` for all TERMINATED_HTTPS listeners. This will prevent issues in following cases:
  * customer does not set any version of TLS protocol
  * customer sets only TLSv1.3 in `tls_versions` which is not compatible with HTTP/2 due to the limitation of HTTP/2 required cipher   `ECDHE-RSA-AES128-GCM-SHA256` only to TLS1.2
* add the TLS1.3 supported ciphers to the `tls_cipher_allow_list`

**Elektra:**
* add tls version selector
* add the TLS1.3 ciphers options

I will also create separate issue to append the negation string `!DHE:!TLSv1:!TLSv1_1` to the generated cipher string (after validation via the allow list) to restrict the ciphers to only TLS1.2 and TLS1.3 protocol versions. This negation string will be part of the AS3 declaration and therefore the Big-IP cipher rule/cipher group configuration. It will not be visible/configurable to/by the customer.

2023-11-21 10:38 UTC, m-kratochvil requested changes
After thorough discussion with @velp we agreed on following updates/changes.

**Octavia F5PD:**
* add the TLS1.3 supported ciphers to the `tls_cipher_allow_list`
* set TLSv1.2 as a default protocol version in `tls_versions` for all TERMINATED_HTTPS listeners. This means we will not support TLSv1.3 alone on a listener but only together with TLS1.2. In my opinion (and also Vadim's) this is justified as there is no known use-case to require only TLS1.3 without a fall-back to TLS1.2, and even with both protocols enabled, TLS1.3 will always have priority for TLS handshake, so TLS1.2 only really serves as a fall-back. Furthermore, it will prevent issues in following cases:
  * customer does not set any version of TLS protocol
  * customer sets only TLSv1.3 in `tls_versions` which is not compatible with HTTP/2 due to the limitation of HTTP/2 required cipher   `ECDHE-RSA-AES128-GCM-SHA256` only to TLS1.2


**Elektra:**
* add tls version selector
* add the TLS1.3 ciphers options

I will also create separate issue to append the negation string `!DHE:!TLSv1:!TLSv1_1` to the generated cipher string (after validation via the allow list) to restrict the ciphers to only TLS1.2 and TLS1.3 protocol versions. This negation string will be part of the AS3 declaration and therefore the Big-IP cipher rule/cipher group configuration. It will not be visible/configurable to/by the customer.

2023-11-22 09:59 UTC, BenjaminLudwigSAP commented
Looks good to me, thanks.
Please add a checkbox list to the original post for a quick overview over subtasks, linking the charts PR and elektra issues/PRr. I will approve this PR once those subtasks are done.

2023-11-22 15:27 UTC, velp commented
@BenjaminLudwigSAP what's the point of creating these checkboxes? This change can be deployed independently and we don't have to wait for change in Elektra (it can be too long).

2023-11-27 13:14 UTC, BenjaminLudwigSAP commented
Hmm you're right, this is independent and does not change default functionality. I'm not sure why I didn't see that. Will approve

2023-11-27 13:14 UTC, BenjaminLudwigSAP approved these changes

2023-11-27 13:20 UTC, m-kratochvil approved these changes

2023-11-29 09:53 UTC, merged