Add L2 rollback
sapcc/octavia-f5-provider-driver pull request #263
Opened 2024-03-18 10:35 UTC by BenjaminLudwigSAP

Add rollback for SelfIP creation.

2024-03-28 20:02 UTC, notandy requested changes
Hi, so I've found multiple exceptions and stopped debugging at some point.

2024-03-28 20:02 UTC, notandy commented on octavia_f5/controller/worker/flows/f5_flows.py
> +        LOG.debug(f"{host}: SelfIPs to add for network {network.id}: {[p.id for p in selfips_to_create]}")
`id` of `network` is dereferenced twice, once in L172, making `network` a string and then again in L178, causing

```
ERROR octavia_f5.controller.worker.l2_sync_manager [-] Failed running sync_l2_selfips_and_subnet_routes_flow for host ...: 'str' object has no attribute 'id'
```

2024-03-28 20:02 UTC, notandy commented on octavia_f5/controller/worker/flows/f5_flows.py
> +        subnet_route_network_part = f5_tasks.get_subnet_route_name(network.id, '')
`network` is a string

2024-03-28 20:02 UTC, notandy commented on octavia_f5/controller/worker/flows/f5_flows.py
> +            subnet_route_name = f5_tasks.get_subnet_route_name(network.id, subnet_id)
`network` is a string

2024-03-28 20:02 UTC, notandy commented on octavia_f5/controller/worker/flows/f5_flows.py
> +
`make_remove_selfips_and_subnet_routes_flow` has a log for subnet routes to be removed(L138), I would expect that create do the same for subnet routes to be added.

2024-03-28 20:02 UTC, notandy commented on octavia_f5/controller/worker/tasks/f5_tasks.py
> +        route_name_name = subnet_route['name']
`subnet_route` is a string

2024-03-28 20:05 UTC, notandy commented
Since this is a very large PR and it's hard to debug every corner case, I'd like to request following addition:

Add a unit tests for all (modified/added) Tasks and Flows, that
* Test Creation of Subnet routes
* Test deletion of subnet routes
* Test creation of selfips
* test removal of selfips
* test replacement of selfip with route (e.g. remove a VIP from subnet)
* test replacement of route with selfip (e.g. added a VIP to subnet)

2024-06-21 14:58 UTC, m-kratochvil commented
From my end this looks good, it's a lot of code which I can't reliably review but I at least went through and checked for anything wrong like typos or mistakes in the comments but everything looks good. We had few discussions with Benjamin on Slack about the networking concepts related to routes and self-IPs on Big-IP so I trust everything is implemented correctly. But I will let Andy or Vadim press the "approve" button, from my end this PR is approved.

2024-06-27 15:04 UTC, velp commented
Looks good to me. Pretty much everything is covered with unit tests (checked coverage report). The logic looks OK for me too. Let's wait final word from Andy.

2024-06-27 15:04 UTC, velp approved these changes

2024-06-27 19:45 UTC, notandy approved these changes
I tested a bit, and apart from minor comment typos it looks good.

2024-06-27 19:45 UTC, notandy commented on octavia_f5/controller/worker/tasks/f5_tasks.py
> +        # Otherwise update existing subnet route (if our route isn't a subset)
the comment seems c&p from the wrong task?

2024-07-23 19:19 UTC, m-kratochvil commented
Checked the last three commits, look good to me, I don't see anything wrong.

2024-07-30 13:22 UTC, merged